---
- name: Provision and Launch the new EC2 Instance
  ec2:
    keypair: "{{ ec2_keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    group_id: "{{ group_id }}"
    wait: true
    count: 1
    instance_tags:
      Name: LAMP Webserver
  register: ec2